# The Microsoft Store screenshots, as recipes rather than as prose.
#
# `take-shots.ps1` beside this takes a set given the recipes for it, and
# `screenshot.ps1` under that is the driver and knows nothing about Odox. Both
# are generated by ship and the same in every repository with a window to
# photograph. This file is the part that is Odox's - which application, which
# document, and what has to happen in the window before the shutter.
#
# Everything a person would change to retake a set lives at the top, and running
# it by hand on the Windows machine is the same command CI would:
#
#     cargo build --release
#     powershell -ExecutionPolicy Bypass -File packaging\windows\shots.ps1
#     ...\shots.ps1 -Only xodt              # one application's frames
#
# WHAT IS PHOTOGRAPHED, WHICH IS NOT SIMPLY "THE DOCUMENT'S APPLICATION"
#
# The executable is launched with the document as an argument, and the
# executable is named rather than inferred. An install here adds each
# application to `OpenWithProgids` and never writes `UserChoice`, so on a
# machine with a full office suite the shell opens the office suite, and a
# script that shelled out to the document would photograph it.
#
# `-Aumid` takes the other route for the case it is good for: the package is
# installed, and what is wanted in the frame is the packaged build rather than
# the release binary it carries. A package declares no execution alias and
# `WindowsApps` is not a directory a script can launch out of, so that is the
# only way in to one.
#
# Something is open in every shot: a screenshot of an empty window is what
# guideline 2.3.3 sends back.
#
# Author: David M. Anderson
# Built with AI assistance (Claude, Anthropic)

[CmdletBinding()]
param(
    # One application's frames rather than all three.
    [ValidateSet('xodt', 'xods', 'xodp')][string] $Only,
    # One plain capture, and nothing else. This is how a coordinate gets
    # measured when a recipe below grows one. With three applications it needs
    # to know which.
    [switch] $Reference,
    [string] $OutDir,
    # The packaged application, as `<PackageFamilyName>!<ApplicationId>`. One
    # per application, so this takes the family name and the application id is
    # the application's own name.
    [string] $Aumid
)

$ErrorActionPreference = 'Stop'

. "$PSScriptRoot\take-shots.ps1"

$root = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path

# --- the configuration ------------------------------------------------------

# The Store's minimum for a desktop screenshot, and not exceeded: a window this
# size looks like a window rather than like an advertisement.
$WIDTH = 1366
$HEIGHT = 768

# The three strings each application needs here. `build-msix.ps1` holds the full
# table and `packaging/macos/build-app.sh` holds the same one in that platform's
# spellings; only these columns are wanted.
$APPLICATIONS = [ordered]@{
    xodt = @{ Executable = 'xodt.exe'; Document = 'corpus\libreoffice\text.odt' }
    xods = @{ Executable = 'xods.exe'; Document = 'corpus\libreoffice\calc.ods' }
    xodp = @{ Executable = 'xodp.exe'; Document = 'corpus\libreoffice\growing-liberty.odp' }
}

# Where the shots land. Not committed: dist is where every built artefact goes.
if (-not $OutDir) { $OutDir = Join-Path $root 'dist\screenshots' }

# A deck whose slides carry pictures is still decoding them when a document of
# a few pages has settled, so xodp waits longer than the driver's default.
$DECK_SETTLE = 8

# --- finding the built executables ------------------------------------------

# Cargo is asked where its target directory is rather than guessed at, because
# `[build] target-dir` in a Cargo configuration file moves it and no environment
# variable then says so. Every packaging script here asks.
function Get-TargetDir {
    if (Get-Command cargo -ErrorAction SilentlyContinue) {
        Push-Location $root
        try {
            $meta = cargo metadata --format-version 1 --no-deps 2>$null | ConvertFrom-Json
            if ($meta) { return $meta.target_directory }
        } finally { Pop-Location }
    }
    return (Join-Path $root 'target')
}
$TARGET = Get-TargetDir

# How one application is opened, with its document.
function Opens([string] $app) {
    $spec = $APPLICATIONS[$app]
    $document = Join-Path $root $spec.Document
    if (-not (Test-Path -LiteralPath $document)) {
        Write-Error "shots.ps1: no document at $document"
    }
    if ($Aumid) { return @('package', "$Aumid!$app", $document) }
    $binary = Join-Path $TARGET "release\$($spec.Executable)"
    if (-not (Test-Path -LiteralPath $binary)) {
        Write-Error "shots.ps1: no executable at $binary - run 'cargo build --release' first, or pass -Aumid to photograph the installed package"
    }
    return @('exe', $binary, $document)
}

# --- the shots --------------------------------------------------------------

# One shot to a line: name, then the actions that put the window into the state
# being photographed, in the order they are given.
#
#   click X,Y     press a control
#   double X,Y    press it twice inside the double-click interval
#   type TEXT     type
#   key NAME      one key, optionally with modifiers: ctrl+a, return
#
# No actions yet. These three applications read a document and do not edit one,
# so the document on screen is what they do; a frame wanting a pane opened or a
# sheet selected takes a coordinate, and a coordinate is read off a reference
# frame rather than guessed:
#
#     powershell -ExecutionPolicy Bypass -File packaging\windows\shots.ps1 -Reference -Only xods
#
function Get-Shots {
    foreach ($app in $APPLICATIONS.Keys) {
        if ($Only -and $app -ne $Only) { continue }
        $settle = if ($app -eq 'xodp') { $DECK_SETTLE } else { 0 }
        Shot "$app-01-document" -Launch (Opens $app) -Process $app -Settle $settle
    }
}

if ($Reference -and -not $Only) {
    Write-Error 'shots.ps1: -Reference needs -Only, because three applications have three windows'
}

$first = if ($Only) { $Only } else { 'xodt' }
Take-Shots -Launch (Opens $first) -Process $first `
    -Width $WIDTH -Height $HEIGHT -OutDir $OutDir -Reference:$Reference
