[package]
name = "xodt"
description = "A small, fast editor for OpenDocument text documents"
keywords = ["opendocument", "odt", "editor", "odf", "egui"]
categories = ["gui", "text-processing"]
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[[bin]]
name = "xodt"
path = "src/main.rs"

[dependencies]
odox-core.workspace = true
odox-ui.workspace = true
eframe.workspace = true
