[package]
name = "xodp"
description = "A small, fast editor for OpenDocument presentations"
keywords = ["opendocument", "odp", "presentation", "odf", "egui"]
categories = ["gui"]
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[[bin]]
name = "xodp"
path = "src/main.rs"

[dependencies]
odox-core.workspace = true
odox-ui.workspace = true
eframe.workspace = true
