#!/bin/sh
# The Mac App Store screenshots, as recipes rather than as prose.
#
# `take-shots.sh` beside this takes a set given the recipes for it, and
# `screenshot.sh` under that is the driver and knows nothing about Odox. Both
# are generated by ship and the same in every repository with a window to
# photograph. This file is the part that is Odox's - which application, which
# document, and what has to happen in the window before the shutter - the
# counterpart of `packaging/windows/shots.ps1`.
#
# One application per run, because the driver photographs a bundle and Odox
# has three: `--app` names which. The workflow calls this once per bundle, the
# way it calls `mac-release-binary` once per bundle; running it by hand on the
# Mac is the same command CI would:
#
#   ./packaging/macos/build-app.sh --all
#   ./packaging/macos/shots.sh --app 'dist/Odox Text.app' --lang de
#   ./packaging/macos/shots.sh --app 'dist/Odox Grid.app' --lang en --reference
#
# WHAT IS PHOTOGRAPHED
#
# A document opened reading, which is what all three do at rest: none of them
# has a control to drive into a more interesting state yet. Something is open
# in every shot regardless - a screenshot of an empty window is what guideline
# 2.3.3 sends back - and a click or a key recipe belongs here the day one of
# them has a panel worth showing selected.
#
# Author: David M. Anderson
# Built with AI assistance (Claude, Anthropic)
set -eu

# The Store's minimum for a desktop screenshot, and not exceeded: a window
# this size looks like a window rather than like an advertisement.
WIDTH=1440
HEIGHT=900

# The three strings each application needs here, keyed by the bundle name
# `build-app.sh` gives it. `packaging/windows/shots.ps1` holds the same table
# in that platform's spellings.
root=$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd)

app_key() {
    case "$(basename "$app" .app)" in
        "Odox Text") echo xodt ;;
        "Odox Grid") echo xods ;;
        "Odox Deck") echo xodp ;;
        *) echo "shots.sh: no recipe for the bundle ${app}" >&2; exit 2 ;;
    esac
}

app_document() {
    case "$1" in
        xodt) echo "${root}/corpus/libreoffice/text.odt" ;;
        xods) echo "${root}/corpus/libreoffice/calc.ods" ;;
        xodp) echo "${root}/corpus/libreoffice/growing-liberty.odp" ;;
    esac
}

# Given a language tag, sets `document` to the file this run opens. The
# document does not vary by language - none of the three carries translated
# content - only the window's own language does, which `screenshot.sh` sets
# through `--lang`.
for_language() {
    document=$(app_document "$(app_key)")
}

# One frame: the document at rest. Named with the application's own key first,
# because all three land in the same locale directory and only the prefix
# tells their frames apart.
#
# A deck whose slides carry pictures is still decoding them when a document of
# a few pages has settled, so xodp waits longer than the driver's default.
shots() {
    key=$(app_key)
    case "$key" in
        xodp) shot "${key}-01-document" --settle 8 ;;
        *) shot "${key}-01-document" ;;
    esac
}

. "$(dirname -- "$0")/take-shots.sh"
take_shots "$@"
